language: cpp
compiler:
  - gcc
jobs:
  include:
    - name: python 2.7
      os: linux
      dist: xenial
      env: PYTHON=2
      before_install:
        - sudo apt-get update
        - sudo apt-get -y install python python-pip python-setuptools python-wheel
      after_success:
        - coveralls --gcov-options '\-lp' -i $PWD/vm/ubpf_vm.c -i $PWD/vm/ubpf_jit_x86_64.c -i $PWD/vm/ubpf_loader.c
    - name: python 3.5
      os: linux
      dist: xenial
      env: PYTHON=3
      before_install:
        - sudo apt-get update
        - sudo apt-get -y install python3 python3-pip python3-setuptools python3-wheel
# command to install dependencies
install: 
  - python$PYTHON -m pip install --user -r requirements.txt
  - python$PYTHON -m pip install --user cpp-coveralls
# command to run tests
script: 
  - make -C vm COVERAGE=1
  - nosetests -v
